app/api/urls.py
from django.conf import settings
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from api.views import (
    AnalizePorPeriodoList,
    AnalizePorProgramaList,
    AudienciaList,
    TempoDisponivelList,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Globo API",
        default_version="1.0.0",
        description="Teste Globo - API",
        contact=openapi.Contact(email=settings.ADMINS[0][1]),
    ),
    public=False,
)


urlpatterns = [
    path("", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("swagger.json", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("audiencia/", AudienciaList.as_view(), name="audiencia",),
    path("tempo-disponivel/", TempoDisponivelList.as_view(), name="audiencia",),
    path("analitico/programa/", AnalizePorProgramaList.as_view(), name="audiencia",),
    path("analitico/periodo/", AnalizePorPeriodoList.as_view(), name="audiencia",),
]

app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from pipeline.views import bad_request, page_not_found, permission_denied, server_error

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls"), name="login"),
    path("", include("pipeline.urls")),
    path("api/", include("api.urls")),
    path(
        "400/",
        bad_request,
        kwargs={"exception": Exception("Requisição mal realizada")},
    ),
    path(
        "403/", permission_denied, kwargs={"exception": Exception("Permisão negada")},
    ),
    path(
        "404/",
        page_not_found,
        kwargs={"exception": Exception("Página não localizada")},
    ),
    path("500/", server_error),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/pipeline/urls.py
from django.urls import path

from pipeline.views import (
    HomeView,
    PipelineAudienciaView,
    PipelineHistoricoView,
    PipelineTempoView,
    index,
    keepalive,
)

urlpatterns = [
    path("", index, name="index"),
    path("home/", HomeView.as_view(), name="home"),
    path("keepalive/", keepalive, name="keepalive"),
    path(
        "pipeline/historico/",
        PipelineHistoricoView.as_view(),
        name="pipeline-historico",
    ),
    path(
        "pipeline/audiencia/",
        PipelineAudienciaView.as_view(),
        name="pipeline-audiencia",
    ),
    path("pipeline/tempo/", PipelineTempoView.as_view(), name="pipeline-tempo"),
]

app/pipeline/models.py
from django.contrib.auth.models import User
from django.db import models


class File(models.Model):

    FILE_AUDIENCIA = "A"
    FILE_TEMPO = "T"
    CHOICE_FILE = (
        (FILE_AUDIENCIA, "Arquivo de audiencia"),
        (FILE_TEMPO, "Arquivo de tempo"),
    )

    tipo_arquivo = models.CharField(
        verbose_name="Tipo do arquivo", max_length=1, choices=CHOICE_FILE
    )
    file = models.FileField(null=True, verbose_name="Arquivo")


class Pipeline(models.Model):

    STATUS_PROCESSANDO = "P"
    STATUS_FINALIZADO = "F"
    STATUS_ERRO = "E"
    CHOICE_STATUS = (
        (STATUS_PROCESSANDO, "Processando"),
        (STATUS_FINALIZADO, "Finalizado"),
        (STATUS_ERRO, "Erro"),
    )

    status = models.CharField(
        verbose_name="Status", max_length=1, choices=CHOICE_STATUS
    )
    finalizado = models.BooleanField(verbose_name="Finalizado?", default=False)
    file = models.ForeignKey(
        File, verbose_name="Arquivo uplaod", on_delete=models.CASCADE
    )

    data_inicio = models.DateTimeField(
        verbose_name="Data/Hora de inicío", auto_now=True
    )
    data_final = models.DateTimeField(
        verbose_name="Data/Hora da final", auto_now=False, null=True, blank=True,
    )
    criado_por = models.ForeignKey(
        User, verbose_name="Criado por", on_delete=models.CASCADE
    )

    class Meta:
        ordering = ["id"]
        verbose_name = "Pipeline"
        verbose_name_plural = "Pipelines"


class Audiencia(models.Model):

    signal = models.CharField(name="signal", max_length=10)
    program_code = models.CharField(name="program_code", max_length=10)
    exhibition_date = models.DateField(
        "exhibition_date", auto_now=False, auto_now_add=False
    )
    program_start_time = models.DateTimeField(
        "program_start_time", auto_now=False, auto_now_add=False
    )
    average_audience = models.DecimalField(
        "average_audience", max_digits=19, decimal_places=10
    )

    class Meta:
        verbose_name = "Audiencia"
        verbose_name_plural = "Audiencias"

    def __str__(self):
        return self.signal


class TempoDisponivel(models.Model):

    signal = models.CharField(name="signal", max_length=10)
    program_code = models.CharField(name="program_code", max_length=10)
    date = models.DateField("date", auto_now=False, auto_now_add=False)
    available_time = models.IntegerField("available_time")

    class Meta:
        verbose_name = "Tempo Disponivel"
        verbose_name_plural = "Tempo Disponivel"

    def __str__(self):
        return self.signal

app/pipeline/forms.py
from django import forms


class UploadFileForm(forms.Form):

    file = forms.FileField(
        label="Arquivo", help_text="Importe o arquivo de formato csv"
    )

app/pipeline/views.py
import csv
import datetime
import logging
from http import HTTPStatus
from typing import Any, Dict

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.http import HttpRequest
from django.shortcuts import HttpResponse, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from pipeline.entity import Zones
from pipeline.forms import UploadFileForm
from pipeline.models import Audiencia
from pipeline.models import File as FileUpload
from pipeline.models import Pipeline, TempoDisponivel

ERROR_TEMPLATE: str = "error.html"
ERROR_BAD_REQUEST: str = "Requisição inválida"

logger = logging.getLogger(__name__)


def bad_request(request: HttpRequest, exception):
    status = HTTPStatus.BAD_REQUEST
    context = {
        "error_menssage": ERROR_BAD_REQUEST,
        "error_status": status.value,
    }
    logger.error(f"Erro: {exception}")
    return render(request, ERROR_TEMPLATE, context, status=status.value)


def permission_denied(request: HttpRequest, exception):
    status = HTTPStatus.FORBIDDEN
    context = {"error_menssage": "Permisão negada.", "error_status": status.value}
    logger.error(f"Erro: {exception}")
    return render(request, ERROR_TEMPLATE, context, status=status.value)


def page_not_found(request: HttpRequest, exception):
    status = HTTPStatus.NOT_FOUND
    context = {"error_menssage": "Página não localizada.", "error_status": status.value}
    logger.error(f"Erro: {exception}")
    return render(request, ERROR_TEMPLATE, context, status=status.value)


def server_error(request: HttpRequest):
    status = HTTPStatus.INTERNAL_SERVER_ERROR
    context = {
        "error_menssage": "Erro interno no servidor.",
        "error_status": status.value,
    }
    return render(request, ERROR_TEMPLATE, context, status=status.value)


@login_required
def keepalive(request):
    html = "<html><body>KeepAlive Ok.</body></html>"
    return HttpResponse(html)


@login_required
def index(request):
    return redirect("login")


class HomeView(View):

    template_name = "home.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        logger.info(f"HomeView {request.method}")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request: HttpRequest, **kwargs):
        return render(request, self.template_name)


class PipelineHistoricoView(ListView):

    template_name = "pipeline-historico.html"
    model = Pipeline
    ordering = ["-data_inicio", "-data_final"]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        logger.info(f"PipelineHistoricoView {request.method}")
        return super().dispatch(request, *args, **kwargs)


class PipelineAudienciaView(FormView):

    template_name = "pipeline-audiencia.html"
    form_class = UploadFileForm
    success_url = reverse_lazy("pipeline-historico")

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        logger.info(f"PipelineAudienciaView {request.method}")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class(self.request.GET)
        return context

    def upload_data_base_file(self, pipeline: Pipeline):
        file_name = pipeline.file.file.path
        delemiter = ","
        with open(file_name, newline="") as csvfile:
            spamreader = csv.reader(csvfile, delimiter=delemiter, quotechar="|")
            index = 0
            for row in spamreader:
                if len(row) != 5:
                    raise Exception("Layout do arquivo incorreto")

                index += 1
                if index == 1:
                    continue
                Audiencia.objects.create(
                    signal=row[0],
                    program_code=row[1],
                    exhibition_date=row[2],
                    program_start_time=row[3],
                    average_audience=row[4],
                )

    def post(self, request: HttpRequest, **kwargs: Any) -> HttpResponse:
        context = super().get_context_data(**kwargs)
        form = self.form_class(request.POST, request.FILES)
        if not form.is_valid():
            messages.add_message(
                request, messages.ERROR, "Erro ao processar arquivo",
            )
            return render(request, self.template_name, context=context)

        file = request.FILES["file"]
        file_create = File(file, f"zone/{Zones.RAW.value}/{file.name}")
        file_upload = FileUpload.objects.create(
            tipo_arquivo=FileUpload.FILE_AUDIENCIA, file=file_create,
        )
        pipeline = Pipeline.objects.create(
            file=file_upload,
            status=Pipeline.STATUS_PROCESSANDO,
            criado_por=request.user,
        )

        try:
            self.upload_data_base_file(pipeline=pipeline)

            pipeline.data_final = datetime.datetime.now()
            pipeline.finalizado = True
            pipeline.status = Pipeline.STATUS_FINALIZADO
            pipeline.save()

            messages.add_message(
                request, messages.SUCCESS, "Arquivo processado com sucesso",
            )

        except Exception as ex:

            pipeline.finalizado = True
            pipeline.status = Pipeline.STATUS_ERRO
            pipeline.save()

            messages.add_message(
                request, messages.ERROR, f"Erro ao processar arquivo - Erro: {ex}",
            )
            return render(request, self.template_name, context=context)

        return redirect(self.success_url)


class PipelineTempoView(FormView):

    template_name = "pipeline-tempo.html"
    form_class = UploadFileForm
    success_url = reverse_lazy("pipeline-historico")

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        logger.info(f"PipelineTempoView {request.method}")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class(self.request.GET)
        return context

    def upload_data_base_file(self, pipeline: Pipeline):
        file_name = pipeline.file.file.path
        delemiter = ";"
        with open(file_name, newline="") as csvfile:
            spamreader = csv.reader(csvfile, delimiter=delemiter, quotechar="|")
            index = 0
            for row in spamreader:
                if len(row) != 4:
                    raise Exception("Layout do arquivo incorreto")

                index += 1
                if index == 1:
                    continue
                date_split = row[2].split("/")
                new_date = f"{date_split[2]}-{date_split[1]}-{date_split[0]}"
                TempoDisponivel.objects.create(
                    signal=row[0],
                    program_code=row[1],
                    date=new_date,
                    available_time=row[3],
                )

    def post(self, request: HttpRequest, **kwargs: Any) -> HttpResponse:
        context = super().get_context_data(**kwargs)
        form = self.form_class(request.POST, request.FILES)
        if not form.is_valid():
            messages.add_message(
                request, messages.ERROR, "Erro ao processar arquivo",
            )
            return render(request, self.template_name, context=context)

        file = request.FILES["file"]
        file_create = File(file, f"zone/{Zones.RAW.value}/{file.name}")
        file_upload = FileUpload.objects.create(
            tipo_arquivo=FileUpload.FILE_TEMPO, file=file_create,
        )
        pipeline = Pipeline.objects.create(
            file=file_upload,
            status=Pipeline.STATUS_PROCESSANDO,
            criado_por=request.user,
        )

        try:
            self.upload_data_base_file(pipeline=pipeline)

            pipeline.data_final = datetime.datetime.now()
            pipeline.finalizado = True
            pipeline.status = Pipeline.STATUS_FINALIZADO
            pipeline.save()

            messages.add_message(
                request, messages.SUCCESS, "Arquivo processado com sucesso",
            )

        except Exception as ex:

            pipeline.finalizado = True
            pipeline.status = Pipeline.STATUS_ERRO
            pipeline.save()

            messages.add_message(
                request, messages.ERROR, f"Erro ao processar arquivo - Erro: {ex}",
            )
            return render(request, self.template_name, context=context)

        return redirect(self.success_url)

app/pipeline/templates/home.html
{% extends 'template.html' %}
{% load static %}

{% comment %} BLOCO DE TITULO DO SITE {% endcomment %}
{% block title %} - Pipelines{% endblock %}
{% block name_page %}Pipelines{% endblock %}
{% block tree_site %}{% endblock %}

{% comment %} BLOCO HEAD {% endcomment %}
{% block head %}

    {% comment %} Intro JS {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/intro-js6.0.0/css/intro.min.css' %}">

{% endblock %}

{% comment %} BLOCO DO CORPO DO HTML {% endcomment %}
{% block body %}

    {% include 'message.html' %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default">

                {% comment %} CARD HEADER {% endcomment %}
                <div class="card-header">
                    <h3 class="card-title text-black-50">Processar pipelines</h3>
                </div>

                {% comment %} CARD BODY {% endcomment %}
                <div class="card-body mt-4">
                    <div class="row">

                        <div class="col-md-4 col-sm-12">
                            <div class="small-box bg-gradient-info">
                                <div class="inner">
                                    <h3>Histórico</h3>
                                    <p>Todos os processos executados</p>
                                </div>
                                <div class="icon">
                                    <i class="nav-icon fas fa-table"></i>
                                </div>
                                <a href="{% url 'pipeline-historico' %}" class="small-box-footer">
                                    Acessar
                                    <em class="fas fa-arrow-circle-right ml-2"></em>
                                </a>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="small-box bg-gradient-primary">
                                <div class="inner">
                                    <h3>Audiência dos programas</h3>
                                    <p>Processar informações históricas de audiência de programas que já foram exibidos.</p>
                                </div>
                                <div class="icon">
                                    <i class="nav-icon fas fa-table"></i>
                                </div>
                                <a href="{% url 'pipeline-audiencia' %}" class="small-box-footer">
                                    Acessar
                                    <em class="fas fa-arrow-circle-right ml-2"></em>
                                </a>
                            </div>
                        </div>

                        {% comment %} Processar audiência histórica {% endcomment %}
                        <div class="col-md-4 col-sm-12">
                            <div class="small-box bg-gradient-secondary">
                                <div class="inner">
                                    <h3>Tempo disponível</h3>
                                    <p>Processar informações do tempo disponível para anúncios em cada programa.</p>
                                </div>
                                <div class="icon">
                                    <i class="nav-icon fas fa-table"></i>
                                </div>
                                <a href="{% url 'pipeline-tempo' %}" class="small-box-footer">
                                    Acessar
                                    <em class="fas fa-arrow-circle-right ml-2"></em>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/pipeline/templates/pipeline-audiencia.html
{% extends 'template.html' %}
{% load static %}
{% load bootstrap4 %}

{% comment %} BLOCO DE TITULO DO SITE {% endcomment %}
{% block title %} - Pipeline{% endblock %}
{% block name_page %}Pipeline{% endblock %}
{% block tree_site %}{% endblock %}

{% comment %} BLOCO DO CORPO DO HTML {% endcomment %}
{% block body %}

    {% include 'message.html' %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default">
                <form method="POST" action="#" id="form" enctype="multipart/form-data">{% csrf_token %}

                    {% comment %} CARD HEADER {% endcomment %}
                    <div class="card-header">
                        <h3 class="card-title text-black-50">Processar pipeline de audiência.</h3>
                    </div>

                    {% comment %} CARD BODY {% endcomment %}
                    <div class="card-body mt-4">
                        <div class="row">
                            {% bootstrap_form form %}
                        </div>
                    </div>

                    {% comment %} CARD FOOTER {% endcomment %}
                    <div class="card-footer">
                        <div class="float-right">
                            <a class="btn btn-secondary mx-1" href="{% url 'home' %}">
                                <em class="fas fa-arrow-left"></em>
                                <span class="ml-2 hide-on-mobile">Voltar</span>
                            </a>
                            <button type="submit" form="form" class="btn btn-primary mx-1" onclick="load_page();">
                                <em class="fas fa-filter"></em>
                                <span class="ml-2 hide-on-mobile">Processar</span>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}

app/pipeline/templates/pipeline-historico.html
{% extends 'template.html' %}
{% load static %}

{% comment %} BLOCO DE TITULO DO SITE {% endcomment %}
{% block title %} - Histórico{% endblock %}
{% block name_page %}Histórico{% endblock %}
{% block tree_site %}{% endblock %}

{% block head %}
    {% comment %} DataTables {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/DataTables/datatables.min.css' %}">
{% endblock %}

{% comment %} BLOCO DO CORPO DO HTML {% endcomment %}
{% block body %}

    {% include 'message.html' %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default">
                {% comment %} CARD HEADER {% endcomment %}
                <div class="card-header">
                    <h3 class="card-title text-black-50">Histórico</h3>
                </div>

                {% comment %} CARD BODY {% endcomment %}
                <div class="card-body mt-4">
                    <div class="row">
                        <div class="col-12">
                            <table id="table" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th id="">#</th>
                                        <th id="">Criado por</th>
                                        <th id="">Data início</th>
                                        <th id="">Data início</th>
                                        <th id="">Tipo arquivo</th>
                                        <th id="">Arquivo</th>
                                        <th id="">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ item.criado_por.get_full_name }}</td>
                                        <td>{{ item.data_inicio }}</td>
                                        <td>{{ item.data_final|default_if_none:"" }}</td>
                                        <td>{{ item.file.get_tipo_arquivo_display }}</td>
                                        <td>{{ item.file.file.name }}</td>
                                        <td>
                                            <span class="badge
                                                {% if item.status == "P" %}badge-warning
                                                {% elif item.status == "F" %}badge-success
                                                {% else %}badge-danger{% endif %}" title="Status" >{{ item.get_status_display }}</span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {% comment %} CARD FOOTER {% endcomment %}
                <div class="card-footer">
                    <div class="float-right">
                        <a class="btn btn-secondary mx-1" href="{% url 'home' %}">
                            <em class="fas fa-arrow-left"></em>
                            <span class="ml-2 hide-on-mobile">Voltar</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block script %}
    {% comment %} DataTables {% endcomment %}
    <script src="{% static 'plugins/DataTables/datatables.min.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            $('#table').DataTable({
                "paging": true,
                "lengthChange": true,
                "ordering": true,
                "order": [],
                "pageLength": 25,
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "searching": true,
                "info": true,
                "autoWidth": false,
                "cell-border": false,
                "responsive": true,
                "language": {
                    "decimal":        "",
                    "emptyTable":     "Nenhum registro encontrado",
                    "info":           "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "infoEmpty":      "Mostrando 0 até 0 de 0 registros",
                    "infoFiltered":   "(Filtrados de _MAX_ registros)",
                    "infoPostFix":    "",
                    "thousands":      ",",
                    "lengthMenu":     "_MENU_ resultados por página",
                    "loadingRecords": "Carregando...",
                    "processing":     "Processando...",
                    "search":         "Busca:",
                    "zeroRecords":    "Nenhum registro encontrado",
                    "paginate": {
                        "next":       "Próximo",
                        "previous":   "Anterior",
                        "first":      "Primeiro",
                        "last":       "Último",
                    },
                    "aria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });
    </script>
{% endblock %}

app/pipeline/templates/pipeline-tempo.html
{% extends 'template.html' %}
{% load static %}
{% load bootstrap4 %}

{% comment %} BLOCO DE TITULO DO SITE {% endcomment %}
{% block title %} - Pipeline{% endblock %}
{% block name_page %}Pipeline{% endblock %}
{% block tree_site %}{% endblock %}

{% comment %} BLOCO DO CORPO DO HTML {% endcomment %}
{% block body %}

    {% include 'message.html' %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default">

                <form method="POST" action="#" id="form" enctype="multipart/form-data">{% csrf_token %}

                    {% comment %} CARD HEADER {% endcomment %}
                    <div class="card-header">
                        <h3 class="card-title text-black-50">Processar pipeline de tempo disponíveis para anúncios.</h3>
                    </div>

                    {% comment %} CARD BODY {% endcomment %}
                    <div class="card-body mt-4">
                        <div class="row">
                            {% bootstrap_form form %}
                        </div>
                    </div>

                    {% comment %} CARD FOOTER {% endcomment %}
                    <div class="card-footer">
                        <div class="float-right">
                            <a class="btn btn-secondary mx-1" href="{% url 'home' %}">
                                <em class="fas fa-arrow-left"></em>
                                <span class="ml-2 hide-on-mobile">Voltar</span>
                            </a>
                            <button type="submit" form="form" class="btn btn-primary mx-1" onclick="load_page();">
                                <em class="fas fa-filter"></em>
                                <span class="ml-2 hide-on-mobile">Processar</span>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}